#!/usr/bin/env ruby
require 'set'

def overlap?(range1, range2)
  range1.cover?(range2.begin) || range2.cover?(range1.begin)
end

def intersect?(brick, other)
  bf = brick[0]
  bt = brick[1]
  of = other[0]
  ot = other[1]

  bx = bf[0]..bt[0]
  by = bf[1]..bt[1]
  bz = bf[2]..bt[2]

  ox = of[0]..ot[0]
  oy = of[1]..ot[1]
  oz = of[2]..ot[2]

  overlap?(bx, ox) && overlap?(by, oy) && overlap?(bz, oz)
end


input     = STDIN.read()

bricks = input.each_line.map do
  _1.strip.split(?~).map { |pos| pos.split(?,).map(&:to_i) }
end

bricks.sort_by! { |from, _| from.last }

zmap = Hash.new { |h, k| h[k] = [] }
bricks.each do |brick|
  (brick.first.last..brick.last.last).each do |z|
    zmap[z] << brick
  end
end

bricks.each do |from, to|
  while from[2] != 1
    spec_brick = [from.clone, to.clone]
    spec_brick[0][2] -= 1
    spec_brick[1][2] -= 1
    z1 = from[2]
    z2 = to[2]
    break if zmap[z1 - 1].any? { |other| intersect?(spec_brick, other) }
    from[2] -= 1
    to[2]   -= 1
    (z1..z2).each {
      zmap[_1].delete([from, to])
      zmap[_1 - 1] << [from, to]
    }
  end
end

bricks.sort_by! { |from, to| [from.last, to.last].min }

sole_supports = Set.new
above = Hash.new { |h, k| h[k] = [] }
below = {}

bricks.each.with_index { |(from, to), bidx|
  spec_brick = [from.clone, to.clone]
  spec_brick[0][2] -= 1
  spec_brick[1][2] -= 1
  supports = bricks.map.with_index
    .select { |other, _| intersect?(spec_brick, other) }
    .reject { |other, _| [from, to] == other }
  supports.map(&:last).each {
    above[_1] << bidx
  }
  below[bidx] = supports.map(&:last)
  if supports.count == 1
    sole_supports << supports.first.last
  end
}

# answer for first part
puts "1: #{bricks.count - sole_supports.count}"

# the second part
sole_supports.sum { |idx|
  fell = Set.new
  fell << idx

  pretenders = Set.new

  above[idx].each { pretenders << _1 }

  falling = true
  while falling
    falling = false

    # to_a to allow modification of pretenders while iterating through it
    pretenders.to_a.each { |wannabe|
      # Check if this wannabe has all their supports removed
      if below[wannabe].all? { fell.include?(_1) }
        pretenders.delete(wannabe)
        fell << wannabe
        above[wannabe].each { pretenders << _1 }
        falling = true
        break
      end
    }
  end

  # Less the brick that was removed
  fell.count - 1
}.tap { puts "2: #{_1}" }
